print("Reglas básicas del ajedrez")
print("1. El ajedrez se juega entre dos personas: uno con piezas blancas y otro con negras.")
print("2. Cada jugador comienza con 16 piezas: 8 peones, 2 torres, 2 caballos, 2 alfiles, 1 reina y 1 rey.")
print("3. El objetivo del juego es hacer jaque mate al rey del oponente.")
print("4. Cada tipo de pieza se mueve diferente:")
print("   - Peón: se mueve 1 casilla hacia adelante (2 si es el primer movimiento).")
print("   - Torre: se mueve en línea recta, vertical u horizontal.")
print("   - Caballo: se mueve en forma de L.")
print("   - Alfil: se mueve en diagonal.")
print("   - Reina: se mueve como la torre y el alfil.")
print("   - Rey: se mueve 1 casilla en cualquier dirección.")
print("5. Si una pieza llega a una casilla ocupada por una pieza enemiga, la puede capturar.")
print("6. El rey no puede moverse a una casilla amenazada por una pieza enemiga.")
print("7. Hay movimientos especiales como el enroque, el peón al paso y la promoción de peón.")
print("8. El juego termina cuando:")
print("   - Se hace jaque mate.")
print("   - Hay tablas (empate).")
print("   - Un jugador se rinde.")